Invertedldx : Invertedldx.o DLListStr.o
	gcc -o Invertedldx Invertedldx.o DLListStr.o

Invertedldx.o : Invertedldx.c Invertedldx.h
	gcc -Wall -Werror -c Invertedldx.c DLListStr.o

DLListStr.o : DLListStr.c DLListStr.h
	gcc -Wall -Werror -c DLListStr.c


